data: {
  "raw": "/Volumes/BassoLabSharedDrives/BassoLabShare/Monkey_Studies/SC_Priors/data/raw",
  "processed": "/Volumes/BassoLabSharedDrives/BassoLabShare/Monkey_Studies/SC_Priors/data/processed",
  "compiled": "/Volumes/BassoLabSharedDrives/BassoLabShare/Monkey_Studies/SC_Priors/data/compiled",
}